New
moevm/oclint_extensions pull request #9
Opened 2023-12-28 21:23 UTC by jcdkiki

build-oclint.sh клонирует репозиторий oclint, сбрасывает его до версии 22.02 (последняя версия на данный момент) и запускает скрипт сборки oclint`а. Это нужно, чтобы собрать нужные файлы для последующей сборки СВОИХ кастомных правил.

CMakeLists.txt -- франкенштейн из файлов CMakeLists.txt oclint`а. Некоторые части были немного переписаны под нужды проекта, некоторые были слепо скопированы. Работает => не трогаю.

tester.py принимает на вход путь до папки с исходным кодом лабораторной/курсовой работы студента (Ivanov_Ivan_cw/src). Сначала скрипт определяет способ сборки. Доступны способы из блока проверки курсовой на e.moevm:
* Один c/c++ файл;
* Makefile;

Далее в папке с исходным кодом работы скрипт создает папку для временных файлов. С этого момента скрипт работает только в ней (для чего это нужно, напишу в самом конце (!!!)). Все файлы копируются во временную папку, после чего в ней запускается [bear](https://github.com/rizsotto/Bear) -- утилита для генерации [compile_commands.json](https://clang.llvm.org/docs/JSONCompilationDatabase.html). Без этого JSON файла oclint будет проверять все файлы по-отдельности без какого-либо контекста, это нам не нужно.

Также правило TooManyConsecutiveIfStatements было мной переименовано в TooLongIfSequence, потому что так банально короче. Теперь можно изменить MAX_IF_SEQUENCE_LEN (по умолчанию равно 5). Подробнее про конфигурацию oclint`а [здесь](https://oclint-docs.readthedocs.io/en/stable/howto/rcfile.html)

(!!!) Утилита bear полноценно СОБИРАЕТ проект со всеми вытекающими: объектные файлы, исполняемый файл, потраченное ВРЕМЯ. Если я правильно понял, изменить это никак нельзя. Если это критично, возможно стоит отказаться от bear и воспользоваться этим:
https://stackoverflow.com/questions/21134120/how-to-turn-makefile-into-json-compilation-database
```bash
make --always-make --dry-run \
 | grep -wE 'gcc|g\+\+' \
 | grep -w '\-c' \
 | jq -nR '[inputs|{directory:".", command:., file: match(" [^ ]+$").string[1:]}]' \
 > compile_commands.json
```
Этот код, похоже, не будет ничего собирать, однако доверия он не вызывает.

Хотелось бы услышать комментарии и критику, в частности критику tester.py. По ощущениям сделал грязь.

2023-12-28 21:29 UTC, jcdkiki commented
Хотелось бы еще поинтересоваться насчет Вашей терминологии: какая мотивация использовать слово "критерий"? В документации oclint`а используется термин "rule", прямой перевод -- "правило", никак не "критерий"

2023-12-29 09:33 UTC, zmm commented
Против слова "правило" ничего не имею, использовал "критерий" просто потому, что не сильно заглядывал в код.

2024-01-09 12:52 UTC, zmm commented on tester.py
> +    for x in content:
Предлагаю убрать логику "понимания способа сборки" и заменить ее на флаг командной строки (эта логика у нас уже есть в вышестоящих скриптах).

2024-01-09 13:01 UTC, zmm commented on tester.py
> +    os.system("rm -rf .tester_tmp")
Как правило, для цепочек скриптов в качестве способа передачи информации о корректности / некорректности работы используют коды возврата. Добавьте в вашем с скрипте выход с ненулевым кодом, если были найдены ошибки в исходниках (с точки зрения линтера) или произошли любые другие нештатные ситуации. 

К нештатным ситуациям я бы отнес любые сбои при запуске внешних команд (это будет такая защита на случай, если мы криво настроим вашу утилиту в рабочем окружении). Поэтому, стоит добавить обработку исключений.

2024-01-09 13:03 UTC, zmm commented on tester.py
> +        os.system(f'/bin/sh -c "oclint --rule=TooLongIfSequence "{file}" | grep etu"')
Я бы вынес в параметры командной строки данного скрипты аргументы для oclint (список используемых правил) - так он станет более гибким. 

grep предлагаю убрать - лучше его заменить на обобщенный анализ фидбека от линтера (есть замечания - выводим их как есть + трубим тревогу, нет замечаний - пишем об этом и выходим спокойно)

2024-01-19 19:24 UTC, mirrin00 requested changes
Коменнтарии (+ часть ещё в коде):
1. Pull-request'ы желательно называть +- осмысленно, чтобы понятно к чему он относится
2. На вики про [сборку](https://github.com/moevm/oclint_extensions/wiki/%D0%A1%D0%B1%D0%BE%D1%80%D0%BA%D0%B0) желательно привести полную команду по установке всего для Ubuntu (как одного из самых попрулярных дистрибутивов)
3. При пересборке почему-то не подтянулись уже собранные объектники
4. В инстуркции явно не хватает подробностей о том, как нужно поставить `oclint` и куда (и нужно ли это делать, потому что судя по скриптам -- нет, а на самом деле да и нужно прочитать [инструкцию по установке](https://oclint-docs.readthedocs.io/en/stable/intro/installation.html)). 
5. Использование `bear` не такая большая проблема, тесты же как-то прогоняются == программа как-то собирается. Вот в этот момент можно вызвать bear.
6. Будет ли работать с компилятором `gcc`, которые используется в проверках (я может быть потом проверю самостоятельно)

В остальном выглядит хорошо, оно работает, есть понимание как делать дальше

2024-01-19 19:24 UTC, mirrin00 commented on install-oclint.sh
> +cp -r oclint/build/oclint-release/lib/* /usr/local/lib/
Заодно нужно это добавить в `CMakeLists.txt`, чтобы там тоже можно было кастомизировать (или предоставить пример, как это сделать, я сходу не помню все возможности cmake)

2024-02-02 17:18 UTC, jcdkiki commented on tester.py
> 1. Что будет, если не использовать `bear` (соответсвенно не использовать `compile_commands.json`)

Размышляя над этим вопросом, пришел к двум выводам:
1. В текущей реализации `tester.py` не проверяет подключаемые заголовочные файлы (а в них тоже можно написать что-нибудь "запрещенное");
2. Критерии, как вы и сказали, действительно не требуют ничего сверхъестественного.

Поэтому вместо `bear` использовать `oclint` напрямую для каждого `.c`/`.cpp`/`.h` файла звучит как хороший вариант. Но здесь, как мне кажется, возникают другие проблемы:

1. В одной из лабораторных мне пришлось воспользоваться `-std=c99`. Причину уже не помню. Может ли oclint, не зная про этот флаг, совершить какую-нибудь ошибку? Стоит это проверять?
2. Студенты могут поэкспериментировать и прийти к выводу, что `.c` файл с русской `с` не проверяется системой ( [Гомоглифы Юникода](https://github.com/codebox/homoglyph/blob/master/raw_data/chars.txt)). С `bear` такой проблемы не возникнет, имена файлов он прослушает правильно. Без `bear` вижу решение только в сообщении: `Ошибка: посторонние файлы в src`.

Может это и не проблемы вовсе, но это было первым, что прошло в голову.

2024-02-03 11:19 UTC, jcdkiki commented
Чуть позже постараюсь прокомментировать и дополнить.

2024-02-04 02:01 UTC, jcdkiki commented
Что сделано:

* В wiki по сборке добавлена команда (TL;DR), устанавливающая все зависимости, собирающая и устанавливающая OCLint и критерии.
* В скрипт `install-oclint.sh` добавлена установка самого бинарника `oclint`.
* Хэш коммита в `build_oclint.sh` вынесен в отдельную переменную. Имя переменной спорно (`OCLINT_22_02_COMMIT`)... С одной стороны, этот репозиторий рассчитал на *конкретную* версию OCLint, а с другой стороны никто не мешает попробовать другие.
* Инструкция сборки в README файле.
* Удален tester.py... Действительно, странная вещь. Заменил ее двумя bash-скриптами внутри папки `examples`. Про них информация в README.

> При пересборке почему-то не подтянулись уже собранные объектники_

При пересборке чего именно? Если при пересборке кастомных критериев, то не знаю в чем дело. Если же при пересборке самого OCLint, то:
1. Не вижу смысла его пересобирать, т.к. от этой сборки конкретно мне нужны только некоторые библиотеки (`.so` и `.a`), которые там собираются. Нужны они, поскольку они линкуются с нашими критериями.
2. Если это действительно критично, тогда не знаю что делать. Скрипт `build` внутри `oclint/oclint-scripts` , насколько я понимаю, собирает `oclint` без никаких лишних телодвижений, ОДНАКО у меня `build` зависает на одном из пунктов (зависает настолько, что компьютер перестает реагировать на любые нажатия клавиш и движения мышью, перезагружаюсь зажатием кнопки питания)

> Будет ли работать с компилятором gcc, которые используется в проверках?

У меня работает (Debian 12). Остальное не могу знать.

2024-02-09 21:20 UTC, jcdkiki commented
* do-everything.sh - это тот самый one-liner, который устанавливает все зависимости, собирает OCLint, собирает наши правила и всё устанавливает
* do-rules.sh - это скрипт, который собирает и устанавливает наши правила без пересборки OCLint`а. Полезен, когда пересобираешь правило по 10 раз. Можно исполнять из любой директории, ничего не поломается. Я лично исполнял внутри examples.
* Переделал примеры. Теперь в них проще ориентироваться.
* Проверка на goto уже реализована в OCLint.
* Новое правило (критерий??????): MallocSizeofRule

2024-03-03 15:03 UTC, AndrewGavril commented
1. Предлагаю объединить скрипты в один в виде функций, чтобы каждый скрипт был автономен и выполнял все шаги с зависимостями. Добавить скрипту аргументы для вызова нужных функций: build, intall deps, install oclint, build examples, run example <example name>. Добавьте скрипту справку по ее использованию. В качестве альтернативы можно использовать существующие скрипты, но в Makefile (там как раз можно проверить установлен ли oclint, сбилжены ли примеры и остальные зависимости для выполнения вышеописанных функций). На текущий момент readme и wiki несколько отличаются и нужно разбираться, чтобы воспроизвести результат. Скрипты должны минимизировать ошибки пользователя.
2, После пункта 1 нужно обновить всю документацию (wiki и readme). В Readme добавить самый простой способ запуска примера, вариации запуска и использования скриптов уже можно вынести на wiki.
3. Добавьте примеры для итогового запуска примера. Я дошел до этапа запуска `test-gcc.sh`, но не знаю параметров oclint. которые нужно передавать.

2024-03-14 16:23 UTC, jcdkiki commented
Создал один большой Makefile, заменяющий все .sh скрипты для установки и сборки всего подряд. Про него можно почитать в обновленном wiki.

README.md тоже был обновлен

2024-03-19 13:36 UTC, jcdkiki commented
[55caf7e](https://github.com/moevm/oclint_extensions/pull/9/commits/55caf7ef20ff8be6f0c5833ff7c742563bffe6fa)

Доделанный TooLongIfSequenceRule

Проверяет подряд идущие if-ы не только на их существование, но и смотрит, какие у этих if-ов условия.  Сравнивая условия, он просто проходится по их синтаксическим деревьям.

Степень "жесткости" проверки можно настраивать. Этот критерий имеет следующие параметры:

MAX_IF_SEQUENCE_LEN (по умолчанию равен 5) - это максимальная разрешенная длина последовательности ифов с похожими условиями

CHECK_BINARY_OPERATOR (по умолчанию равен 1) - если равен единице, тогда критерий будет смотреть на знаки в условиях if-ов. Например, "x < 5" и "x > 5" для него будут разными условиями. Чтобы выключить такое поведение, надо присвоить этому параметру значение 0.

CHECK_FUNCTION_CALL (по умолчанию равен 1) - если равен единице, тогда критерий будет смотреть на то, какие функции вызываются внутри условий if-ов. Например, "gcd(x, y)" и "lcm(x, y)" для него будут разными выражениями и условия, их содержащие, будут тоже считаться непохожими. Чтобы выключить такое поведение, надо присвоить этому параметру значение 0.

Напомню, как передавать параметры OCLint`у:

через флажок -rc:
```
-rc=PARAMETER=VALUE
```

т.е. можно писать так:
```
examples/test-gcc.sh examples/ex-if -rc=CHECK_FUNCTION_CALL=0 -rc=MAX_IF_SEQUENCE_LEN=7
```

2024-07-05 07:01 UTC, thehighestmath commented
Вроде всё делал по инструкции, а сборка сломалась 
```
➜  oclint_extensions git:(new) sudo make install
[sudo] password for kirillkry: 
apt install -y ninja-build cmake bear
echo "install deps: OK"
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  cloud-guest-utils eatmydata libeatmydata1 libpkcs11-helper1 libsysmetrics1
  python-babel-localedata python3-babel python3-configobj python3-jinja2
  python3-json-pointer python3-jsonpatch python3-jsonschema python3-pyrsistent
  python3-serial
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  cmake-data dh-elpa-helper libear libfmt8 libgrpc++1 libgrpc10 libjsoncpp25
  librhash0 libspdlog1
Suggested packages:
  cmake-doc cmake-format
The following NEW packages will be installed:
  bear cmake cmake-data dh-elpa-helper libear libfmt8 libgrpc++1 libgrpc10
  libjsoncpp25 librhash0 libspdlog1 ninja-build
0 upgraded, 12 newly installed, 0 to remove and 12 not upgraded.
Need to get 9,790 kB of archives.
After this operation, 43.4 MB of additional disk space will be used.
Get:1 https://mirror.yandex.ru/ubuntu jammy/universe amd64 libfmt8 amd64 8.1.1+ds1-2 [60.2 kB]
Get:2 https://mirror.yandex.ru/ubuntu jammy/universe amd64 libgrpc10 amd64 1.30.2-3build6 [1,470 kB]
Get:3 https://mirror.yandex.ru/ubuntu jammy/universe amd64 libgrpc++1 amd64 1.30.2-3build6 [402 kB]
Get:4 https://mirror.yandex.ru/ubuntu jammy/universe amd64 libspdlog1 amd64 1:1.9.2+ds-0.2 [126 kB]
Get:5 https://mirror.yandex.ru/ubuntu jammy/universe amd64 libear amd64 3.0.18-1 [138 kB]
Get:6 https://mirror.yandex.ru/ubuntu jammy/universe amd64 bear amd64 3.0.18-1 [348 kB]
Get:7 https://mirror.yandex.ru/ubuntu jammy/main amd64 libjsoncpp25 amd64 1.9.5-3 [80.0 kB]
Get:8 https://mirror.yandex.ru/ubuntu jammy/main amd64 librhash0 amd64 1.4.2-1ubuntu1 [125 kB]
Get:9 https://mirror.yandex.ru/ubuntu jammy/main amd64 dh-elpa-helper all 2.0.9ubuntu1 [7,610 B]
Get:10 https://mirror.yandex.ru/ubuntu jammy-updates/main amd64 cmake-data all 3.22.1-1ubuntu1.22.04.2 [1,913 kB]
Get:11 https://mirror.yandex.ru/ubuntu jammy-updates/main amd64 cmake amd64 3.22.1-1ubuntu1.22.04.2 [5,010 kB]
Get:12 https://mirror.yandex.ru/ubuntu jammy/universe amd64 ninja-build amd64 1.10.1-1 [111 kB]
Fetched 9,790 kB in 2s (5,219 kB/s)    
Selecting previously unselected package libfmt8:amd64.
(Reading database ... 246958 files and directories currently installed.)
Preparing to unpack .../00-libfmt8_8.1.1+ds1-2_amd64.deb ...
Unpacking libfmt8:amd64 (8.1.1+ds1-2) ...
Selecting previously unselected package libgrpc10:amd64.
Preparing to unpack .../01-libgrpc10_1.30.2-3build6_amd64.deb ...
Unpacking libgrpc10:amd64 (1.30.2-3build6) ...
Selecting previously unselected package libgrpc++1:amd64.
Preparing to unpack .../02-libgrpc++1_1.30.2-3build6_amd64.deb ...
Unpacking libgrpc++1:amd64 (1.30.2-3build6) ...
Selecting previously unselected package libspdlog1:amd64.
Preparing to unpack .../03-libspdlog1_1%3a1.9.2+ds-0.2_amd64.deb ...
Unpacking libspdlog1:amd64 (1:1.9.2+ds-0.2) ...
Selecting previously unselected package libear:amd64.
Preparing to unpack .../04-libear_3.0.18-1_amd64.deb ...
Unpacking libear:amd64 (3.0.18-1) ...
Selecting previously unselected package bear.
Preparing to unpack .../05-bear_3.0.18-1_amd64.deb ...
Unpacking bear (3.0.18-1) ...
Selecting previously unselected package libjsoncpp25:amd64.
Preparing to unpack .../06-libjsoncpp25_1.9.5-3_amd64.deb ...
Unpacking libjsoncpp25:amd64 (1.9.5-3) ...
Selecting previously unselected package librhash0:amd64.
Preparing to unpack .../07-librhash0_1.4.2-1ubuntu1_amd64.deb ...
Unpacking librhash0:amd64 (1.4.2-1ubuntu1) ...
Selecting previously unselected package dh-elpa-helper.
Preparing to unpack .../08-dh-elpa-helper_2.0.9ubuntu1_all.deb ...
Unpacking dh-elpa-helper (2.0.9ubuntu1) ...
Selecting previously unselected package cmake-data.
Preparing to unpack .../09-cmake-data_3.22.1-1ubuntu1.22.04.2_all.deb ...
Unpacking cmake-data (3.22.1-1ubuntu1.22.04.2) ...
Selecting previously unselected package cmake.
Preparing to unpack .../10-cmake_3.22.1-1ubuntu1.22.04.2_amd64.deb ...
Unpacking cmake (3.22.1-1ubuntu1.22.04.2) ...
Selecting previously unselected package ninja-build.
Preparing to unpack .../11-ninja-build_1.10.1-1_amd64.deb ...
Unpacking ninja-build (1.10.1-1) ...
Setting up ninja-build (1.10.1-1) ...
Setting up libgrpc10:amd64 (1.30.2-3build6) ...
Setting up dh-elpa-helper (2.0.9ubuntu1) ...
Setting up libjsoncpp25:amd64 (1.9.5-3) ...
Setting up librhash0:amd64 (1.4.2-1ubuntu1) ...
Setting up libfmt8:amd64 (8.1.1+ds1-2) ...
Setting up libspdlog1:amd64 (1:1.9.2+ds-0.2) ...
Setting up cmake-data (3.22.1-1ubuntu1.22.04.2) ...
Setting up libgrpc++1:amd64 (1.30.2-3build6) ...
Setting up libear:amd64 (3.0.18-1) ...
Setting up bear (3.0.18-1) ...
Setting up cmake (3.22.1-1ubuntu1.22.04.2) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.8) ...
install deps: OK
Cloning into 'oclint-json-compilation-database'...
remote: Enumerating objects: 91, done.
remote: Total 91 (delta 0), reused 0 (delta 0), pack-reused 91
Receiving objects: 100% (91/91), 18.16 KiB | 476.00 KiB/s, done.
Resolving deltas: 100% (41/41), done.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  514M  100  514M    0     0  10.1M      0  0:00:50  0:00:50 --:--:-- 10.2M
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
LLVM_ROOT: /home/kirillkry/moevm/oclint_extensions/oclint/build/llvm-install
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found LLVM LLVM_PACKAGE_VERSION: 13.0.1 - LLVM_VERSION_RELEASE: 13.0.1
-- Using LLVMConfig.cmake in: /home/kirillkry/moevm/oclint_extensions/oclint/build/llvm-install/lib/cmake/llvm
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kirillkry/moevm/oclint_extensions/oclint/build/oclint-core
[13/13] Linking CXX static library lib/libOCLintCore.a
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
LLVM_ROOT: /home/kirillkry/moevm/oclint_extensions/oclint/build/llvm-install
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found LLVM LLVM_PACKAGE_VERSION: 13.0.1 - LLVM_VERSION_RELEASE: 13.0.1
-- Using LLVMConfig.cmake in: /home/kirillkry/moevm/oclint_extensions/oclint/build/llvm-install/lib/cmake/llvm
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kirillkry/moevm/oclint_extensions/oclint/build/oclint-metrics
[5/5] Linking CXX static library lib/libOCLintMetric.a
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
- [...]

2024-07-22 07:06 UTC, merged